remove validate_qobj
Qiskit/qiskit-ibmq-provider pull request #1007
Opened 2021-07-15 18:49 UTC by Rcuz8

### Summary

Validation is being changed in Qiskit Terra. References in Qiskit Provider need to be removed.

### Details and comments

- Removes the validation step, coming from `validate_qobj` in `IBMQBackend`

2021-07-15 19:27 UTC, rathishcholarajan requested changes
@Rcuz8 could you search for all occurrences of `validate_qobj=True` in tests and remove all of them? I see more.

2021-07-15 19:27 UTC, rathishcholarajan commented on qiskit/providers/ibmq/ibmqbackend.py
> -            The following arguments are NOT applicable if a Qobj is passed in.
This line should not be removed.

2021-07-15 19:29 UTC, rathishcholarajan commented
Please add a release note for removal of this keyword.

2021-07-15 19:59 UTC, Rcuz8 commented
@rathishcholarajan Updated! Removed the `validate=True` refs & added the release note. Weird that the tests (lint or otherwise) didn't catch the extra param going into `backend.run()`..

2021-07-15 21:12 UTC, rathishcholarajan requested changes
Looks good! added few suggestions in release notes.

2021-07-16 17:34 UTC, rathishcholarajan approved these changes
Looks great! Thanks @Rcuz8!

2021-07-16 17:35 UTC, merged