add `is_public` to `create_program`
Qiskit/qiskit-ibmq-provider pull request #1026
Opened 2021-07-29 08:49 UTC by Rcuz8

### Summary

Adds `is_public` as param for uploading runtime program.

### Details and comments

Fixes #1006

2021-07-29 14:25 UTC, rathishcholarajan requested changes
@Rcuz8 Thanks. Left some comments and suggestions. Could you also add some unit and integration tests?

2021-07-29 14:25 UTC, rathishcholarajan commented on releasenotes/notes/add-is_public-on-upload-program-5b5bb13912a8cf67.yaml
> +    :meth:`qiskit.providers.ibmq.api.rest.runtime.Runtime.create_program`.
```suggestion
    :meth:`qiskit.providers.ibmq.runtime.IBMRuntimeService.upload_program`.

```

2021-07-29 14:25 UTC, rathishcholarajan commented on releasenotes/notes/add-is_public-on-upload-program-5b5bb13912a8cf67.yaml
> +    A runtime program's visibility can now be specified on upload in:
```suggestion
    A runtime program's visibility can now be specified on upload using `is_public` parameter in 
```

2021-07-29 14:25 UTC, rathishcholarajan commented on qiskit/providers/ibmq/runtime/ibm_runtime_service.py
> +            is_public: Optional[bool] = None,
Could we make it False by default?

2021-08-02 13:58 UTC, Rcuz8 commented on qiskit/providers/ibmq/runtime/ibm_runtime_service.py
> +            is_public: Optional[bool] = None,
Updated!

2021-08-02 13:59 UTC, Rcuz8 commented on releasenotes/notes/add-is_public-on-upload-program-5b5bb13912a8cf67.yaml
> +    A runtime program's visibility can now be specified on upload in:
Updated!

2021-08-02 13:59 UTC, Rcuz8 commented on releasenotes/notes/add-is_public-on-upload-program-5b5bb13912a8cf67.yaml
> +    :meth:`qiskit.providers.ibmq.api.rest.runtime.Runtime.create_program`.
Updated!

2021-08-02 19:28 UTC, rathishcholarajan requested changes
@Rcuz8 Looks good! Left some suggestions...

2021-08-02 19:28 UTC, rathishcholarajan commented on test/ibmq/runtime/test_runtime.py
> +        program_id = self._upload_program(max_execution_time=max_execution_time,
```suggestion
        is_public = True
        program_id = self._upload_program(max_execution_time=max_execution_time,
```

2021-08-02 19:28 UTC, rathishcholarajan commented on test/ibmq/runtime/test_runtime.py
> +                                          is_public=True)
```suggestion
                                          is_public=is_public)
```

2021-08-02 19:28 UTC, rathishcholarajan commented on test/ibmq/runtime/test_runtime.py
> +        self.assertEqual(program._is_public, True)
```suggestion
        self.assertEqual(program.is_public, is_public)
```

2021-08-02 19:28 UTC, rathishcholarajan commented on test/ibmq/runtime/test_runtime_integration.py
> +        program_id = self._upload_program(max_execution_time=max_execution_time,
```suggestion
        is_public = True
        program_id = self._upload_program(max_execution_time=max_execution_time,
```

2021-08-02 19:28 UTC, rathishcholarajan commented on test/ibmq/runtime/test_runtime_integration.py
> +                                          is_public=True)
```suggestion
                                          is_public=is_public)
```

2021-08-02 19:28 UTC, rathishcholarajan commented on test/ibmq/runtime/test_runtime_integration.py
> +        self.assertEqual(program.is_public, True)
```suggestion
        self.assertEqual(program.is_public, is_public)
```

2021-08-06 20:45 UTC, closed without merging